/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fifa14;
import static fifa14.Torneo.equipos;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Cristina Hernández
 */
public class JFAdm extends javax.swing.JFrame {
JFileChooser seleccionado= new JFileChooser();
File archivo;// un fichero
byte[] bytesImg;
Torneo torneo= new Torneo();
GestionA gestion=new GestionA();

      DefaultTableModel modeloTabla ;
      // cada fila de la tabla
      Vector fila = new Vector();
    /**
     * Creates new form JFAdm
     */
    public JFAdm() {
        initComponents();
        
        // se crea el modelo de la tabla
        modeloTabla = new DefaultTableModel();
        
        // se crean las columnas
        modeloTabla.addColumn("Jugador");
        modeloTabla.addColumn("Selección");
        
        // se indica que la tabla va trabajar con este modelo
        tblJugadoresAgregados.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        modalidad = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxJugador = new javax.swing.JComboBox();
        cboTipoTorneo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jlbSeleccionModalidad = new javax.swing.JLabel();
        rbtnTvsT = new javax.swing.JRadioButton();
        rbtnClasif = new javax.swing.JRadioButton();
        rbtnElimDirecta = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstItems = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreJugador = new javax.swing.JTextField();
        btnAgregarJugador = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardarTorneo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblJugadoresAgregados = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");
        jScrollPane1.setViewportView(jLabel1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIFA 14");
        setBackground(new java.awt.Color(51, 255, 204));
        setForeground(new java.awt.Color(102, 255, 204));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("                                                                                     FIFA 14");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Instrucciones:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Para crear un nuevo torneo seleccione la cantidad de jugadores, la modalidad y el Club o la Seleccion.  Guarde la configuración.");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setText("Creación de partidos");

        cbxJugador.setBackground(new java.awt.Color(153, 255, 255));
        cbxJugador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "8", "10", "12", "14", "16", "18", "20", "22", "24", "26", "28", "30", "32" }));
        cbxJugador.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cbxJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxJugadorActionPerformed(evt);
            }
        });

        cboTipoTorneo.setBackground(new java.awt.Color(153, 255, 255));
        cboTipoTorneo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciones", "Clubes" }));
        cboTipoTorneo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cboTipoTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoTorneoActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbSeleccionModalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbSeleccionModalidad.setText("Seleccione la modalidad:");

        modalidad.add(rbtnTvsT);
        rbtnTvsT.setText("Todos vs Todos");
        rbtnTvsT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnTvsTMouseClicked(evt);
            }
        });
        rbtnTvsT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTvsTActionPerformed(evt);
            }
        });

        modalidad.add(rbtnClasif);
        rbtnClasif.setText("Clasificación");
        rbtnClasif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnClasifMouseClicked(evt);
            }
        });
        rbtnClasif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnClasifActionPerformed(evt);
            }
        });

        modalidad.add(rbtnElimDirecta);
        rbtnElimDirecta.setText("Eliminación Directa");
        rbtnElimDirecta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnElimDirectaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbSeleccionModalidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(rbtnTvsT)
                .addGap(18, 18, 18)
                .addComponent(rbtnClasif)
                .addGap(18, 18, 18)
                .addComponent(rbtnElimDirecta)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSeleccionModalidad)
                    .addComponent(rbtnTvsT)
                    .addComponent(rbtnClasif)
                    .addComponent(rbtnElimDirecta))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Seleccione la cantidad de jugadores");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Seleccione el tipo de torneo");

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        lstItems.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstItems.setName("lstvItem"); // NOI18N
        jScrollPane2.setViewportView(lstItems);

        jLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel3.setText("Elija una  selección o un Club");

        jLabel10.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel10.setText("Nombre del jugador");

        txtNombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreJugadorActionPerformed(evt);
            }
        });

        btnAgregarJugador.setText("Agrega Jugador");
        btnAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAgregarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreJugador)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarJugador)
                .addGap(22, 22, 22))
        );

        btnEditar.setText("Editar Torneo");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Torneo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardarTorneo.setText("Guardar ");
        btnGuardarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTorneoActionPerformed(evt);
            }
        });

        jLabel11.setText("Jugadores agregados");

        tblJugadoresAgregados.setBackground(new java.awt.Color(153, 255, 204));
        tblJugadoresAgregados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Jugador", "Selección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblJugadoresAgregados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboTipoTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnEditar)
                        .addGap(150, 150, 150)
                        .addComponent(btnEliminar)
                        .addGap(124, 124, 124)
                        .addComponent(btnGuardarTorneo)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipoTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarTorneo)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(570, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 616, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        this.dispose();//se oculta la ventana

        Principal frame = new Principal();
        frame.setVisible (true);

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTorneoActionPerformed
        String linea="";
        // obtenemos la cantida de jugadores
        int cantidadJugadores = Integer.parseInt(cbxJugador.getSelectedItem().toString());

        // se verifica que todos los equipos estén
        if(Torneo.equipos.size() == cantidadJugadores)
        {
            Torneo torneo= new Torneo();//se crea el objeto torneo de tipo Torneo

            // establecer las propiedad tipotorneo, seleccionPrincipal, cantidadJugadores
            //Creo una variable y la convierto en Entero
            Torneo.cantidadJugadores  = cantidadJugadores;

            cboTipoTorneo.getSelectedIndex();//Obtengo la seleccion del tipo de torneo
            //Guardo ese item en setTipoTorneo
            Torneo.tipoTorneo = cboTipoTorneo.getSelectedIndex();

            lstItems.getSelectedValue().toString();
            Torneo.seleccionPrincipal=lstItems.getSelectedValue().toString();

            if(rbtnTvsT.isSelected()){//si está seleccionado
                Torneo.tipoModalidad= 0;//aqui establecemos el tipo de modalidad todos vs todos
                torneo.llenarTorneoTCT();
                //
            }
            if(rbtnClasif.isSelected()){
                Torneo.tipoModalidad=1;// modalidad Clasificacion
            }
            if(rbtnElimDirecta.isSelected()){
                Torneo.tipoModalidad=2; //modalidad Eliminacion Directa
            }

        }

        else
        {
            JOptionPane.showMessageDialog(null, "Todos los jugadores deben seleccionar un equipo");
        }
        
        try{
            //se abre el archivo y se prepara el mismo para la escritura de lineas en el BufferedWriter
            BufferedWriter bw= new BufferedWriter(new FileWriter ("C:\\Users\\Isabel Cristina\\Desktop\\Torneos\\FIFA14.txt"));
            
            //se extrae la información
            
            Torneo.cantidadJugadores  = cantidadJugadores;
            Torneo.tipoTorneo = cboTipoTorneo.getSelectedIndex();
            Torneo.seleccionPrincipal=lstItems.getSelectedValue().toString();
            
            //se extrae la informacion ingresada mediante los textfield y demás botones se crea una sola linea de texto
            linea= txtNombreJugador.getName()+" "+cantidadJugadores+" "+cboTipoTorneo.getSelectedIndex()+" "+lstItems.getSelectedValue().toString()+" "
                    + " "+Torneo.tipoModalidad+" "+equipos;
            
            //se toma la variable "linea" que contiene toda la informacion digitada y se escribe en el archivo
            bw.write(linea);
            
            //se le indica al archivo de texto que se crea una nueva linea en blanco y queda listo para agregar mas informacion
            bw.newLine();
            
            //se cierra la coneccion con el archivo de texto
            bw.close();
            JOptionPane.showMessageDialog(null,"El archivo se ha guardado correctamente","INFORMACIÓN",
                JOptionPane.INFORMATION_MESSAGE);
                    
            
        
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Se produjo el siguiente error en la generacion del archivo"+ex,"Error",JOptionPane.INFORMATION_MESSAGE);
    }
        /*
        String linea="";
        String cantJug="";
        String tipoTorneo="";
        String TvsT="";

        try
        {//Se abre el archivo y se prepara el mismo para la escritura de lineas en el
            BufferedWriter bw=new BufferedWriter(new FileWriter("D:\\ArchivoTXT\\Agenda.txt"));
            //se extrae la cantidad de jugadores e informacion
            if(cbxJugador.isSelected())
            {
                cantJug="Cantidad de Jugadores: ";
            }
            else if(cboTipoTorneo.isSelected())
            {
                tipoTorneo="Tipo de Torneo: ";
            }
            else if(rbtnTvsT.isSelected())
            {
                TvsT="Trabajo";
            }
           

        */
    }//GEN-LAST:event_btnGuardarTorneoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        /*
        txtNombre.setText("");
        txtGFavor.setText("");
        txtGContra.setText("");
        txtPJugados.setText("");
        txtPGanados.setText("");
        txtPPerdidos.setText("");
        txtPEmpatados.setText("");
        txtGDiferencia.setText("");
        txtPtosObt.setText("");
        */

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJugadorActionPerformed
        // TODO add your handling code here:0

        if(txtNombreJugador.getText().trim().length()==0)
        {
            JOptionPane.showMessageDialog(this, "El campo de texto Nombre está vacío");
        }
        else
        {

            if(lstItems.getSelectedValue() == null){
                JOptionPane.showMessageDialog(null, "Debe elegir un equipo o selección");
            }
            else {

                String equipoSeleccionado= lstItems.getSelectedValue().toString();
                if(torneo.VerificarEquipo(equipoSeleccionado)){
                    JOptionPane.showMessageDialog(null, "Seleccione otro equipo");
                }
                else{

                    Equipo equipo = new Equipo();//clase de cada equipo con la informacion
                    equipo.setId(Torneo.equipos.size());
                    equipo.setAlias(txtNombreJugador.getText());//se establece el nombre del jugador y se guarda en el objeto equipo
                    equipo.setNombre(equipoSeleccionado);// se establece la seleccion de la lista, devuelve un objeto y este se convierte a string

                    // representación de nuestra fila
                    fila = new Vector();

                    // establecemos el nombre del jugador
                    fila.add(equipo.getAlias());

                    // establecemos el nombre del equipo
                    fila.add(equipo.getNombre());

                    // se agrega la fila
                    modeloTabla.addRow(fila);

                    //el primer parametro corresponde al valor digitado, el seg el numero de fila, el terc es la columna
                    int cantidadJugadoresSeleccionados = Integer.parseInt(cbxJugador.getSelectedItem().toString());

                    Torneo.equipos.add(equipo);//se envia el objto equipo

                    if(Torneo.equipos.size() == cantidadJugadoresSeleccionados )//si esta llena la tabla
                    {
                        btnAgregarJugador.setEnabled(false);//desabilita el boton agregar.
                    }
                }
            }
        }

    }//GEN-LAST:event_btnAgregarJugadorActionPerformed

    private void txtNombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreJugadorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNombreJugadorActionPerformed

    private void rbtnElimDirectaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnElimDirectaMouseClicked
        // codigo del radio Eliminacion Directa
        gestion.getModalidad(this.rbtnElimDirecta.getLabel());
    }//GEN-LAST:event_rbtnElimDirectaMouseClicked

    private void rbtnClasifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnClasifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnClasifActionPerformed

    private void rbtnClasifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnClasifMouseClicked
        // codigo del radio clasificacion
        gestion.getModalidad(this.rbtnClasif.getLabel());
    }//GEN-LAST:event_rbtnClasifMouseClicked

    private void rbtnTvsTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTvsTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTvsTActionPerformed

    private void rbtnTvsTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnTvsTMouseClicked
        // codigo del radio todos vs todos
        gestion.getModalidad(this.rbtnTvsT.getLabel());//guarda el laber del todos vs todos
    }//GEN-LAST:event_rbtnTvsTMouseClicked

    private void cboTipoTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoTorneoActionPerformed
        // TODO add your handling code here:

        // obtener el nombre del torneo que el usuaio seleccionó
        String tipoTorneo = cboTipoTorneo.getSelectedItem().toString();

        if(tipoTorneo.equals("Selecciones"))
        {
            cargarArchivo("C:\\Users\\Isabel Cristina\\Desktop\\selecciones\\selecciones.txt");

        }
        else
        {
            // cargamos los clubes
            cargarArchivo("C:\\Users\\Isabel Cristina\\Desktop\\selecciones\\Clubes de FIFA\\Clubes.txt");
        }

    }//GEN-LAST:event_cboTipoTorneoActionPerformed

    private void cbxJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxJugadorActionPerformed

    

    
    private void cargarArchivo(String nombreArchivo)
    {
        // cargamos las selecciones 
            try
            {
                // modelo que representa la lista, lo creamos para agregar los items en él
                DefaultListModel listModel = new DefaultListModel();
                
                // leemos lo que está en el txt
                BufferedReader br = new BufferedReader(new FileReader(nombreArchivo));
                
                // el string builder nos ofrece una mejor opción para concatenar 
                StringBuilder stringBuilder = new StringBuilder();
                
                // leemos la primer línea
                String linea = br.readLine();

                // verificamos si la línea es diferente de null
                while (linea != null) {
                    // concatenamos la línea
                    stringBuilder.append(linea);
                    
                    // concatenamos un salto de línea, un salto de línea
                    stringBuilder.append(System.lineSeparator());
                    
                    // agregamos la línea leída en el modelo de la lista
                    listModel.addElement(linea);
                    
                    // leemos la siguiente línea
                    linea = br.readLine();
                    
                }
                
                // establecemos el modelo de la lista
                lstItems.setModel(listModel);
                
               
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.toString());
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarJugador;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarTorneo;
    private javax.swing.JButton btnRegresar;
    public static javax.swing.JComboBox cboTipoTorneo;
    public static javax.swing.JComboBox cbxJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel jlbSeleccionModalidad;
    private javax.swing.JList lstItems;
    public static javax.swing.ButtonGroup modalidad;
    private javax.swing.JRadioButton rbtnClasif;
    private javax.swing.JRadioButton rbtnElimDirecta;
    private javax.swing.JRadioButton rbtnTvsT;
    private javax.swing.JTable tblJugadoresAgregados;
    private javax.swing.JTextField txtNombreJugador;
    // End of variables declaration//GEN-END:variables
}
